#!/bin/bash

echo -n "Are you ok? (y/n): "
read c
if [ "$c" != "y" ]; then
  exit
fi


heroku=https://nni43-repo.herokuapp.com
github=https://repo.4nni3.com


function getCtrl(){
  local deb="$1"

  pkg=$(dpkg-deb -f "$deb" package)
  vsn=$(dpkg-deb -f "$deb" version)

  json="dp/data/$p.json"
  img="null"
  if [ -e "$json" ]; then
    img=$(jq -r '.icon' "$json")
  fi

  icon=''
  if [ -z "$(dpkg-deb -f "$deb" icon)" -a "$img" != "null" ]; then
    icon="
Icon: ${img}"
  fi

  cat << EOS
$(dpkg-deb -f "$deb")
Depiction: ${heroku}/dp/?p=${pkg}&v=${vsn}
SileoDepiction: ${heroku}/dp/sileo.php?p=${pkg}&v=${vsn}
Filename: ${github}/${deb}
Size: $(wc -c "$deb" | awk '{ print $1 }')
MD5sum: $(md5 -r "$deb" | awk '{ print $1 }')
SHA256: $(shasum -a 256 "$deb" | awk '{ print $1 }')${icon}
EOS

  echo "$ctrl"
  return 0
}

cd $(dirname $0)

rm -rf Package* secret/Package*

touch Packages
for deb in debs/*.deb; do
  echo "$deb"
  getCtrl "$deb" >> Packages
done
cp Packages Packages.txt
bzip2 Packages


cp Packages.txt secret/Packages
touch secret/Packages
for deb in secret/debs/*.deb; do
  echo "$deb"
  getCtrl "$deb" >> secret/Packages
done
cp secret/Packages secret/Packages.txt
bzip2 secret/Packages


git add .
git commit -m "update $(date +%Y%m%d%H%M)"
git push -f origin master


exit

# clear cloudflare cache
curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CFZONE}/purge_cache" \
    -H "Content-Type:application/json" \
    -H "X-Auth-Key: ${CFKEY}" \
    -H "X-Auth-Email: ${CFMAIL}" \
    --data '{ "purge_everything": true }'
echo

